version: '3.8'
services:

  db:
    image: postgres:latest
    container_name: db
    hostname: local
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  db: